### ISSUE TITLE
PolarionIds verification/validation do not detect polarion IDs if they are not passed as str to the pytest marker

### ISSUE THREAD

**Issue by ibesso-rh** [RedHatQE/flake8-plugins#1]
I encountered several pre-commit check failures while working on a gerrit PR which tests the vm_template metrics epic.
The failures disclose issues with the polarion IDs check.

Below, I describe the three unsuccessful attempts to pass the pre-commit checks.
All attempts were executed in the listed order chronologically.

## First attempt: all pytest.param items are created on a separate function
The following error message was displayed when I created a single function that returned a list of pytest.param items. The function was called from within the parametrize context and the list unpacked.
```flake8...................................................................Failed
- hook id: flake8
- exit code: 1
tests/metrics/test_vm_template_metrics.py:123:5: PID001: [test_vmi_phase_count_metric ()], Polarion ID is missing
```

You will see the cnv-tests-gate job that failed CI in that particular patch set.

Here are the two reasons why the error was wrong or was displayed because of flake8 being unable to locate the polarion markers:
* polarion test cases were checked as part of the "make check" execution before i committed.
* skipif marker (which I also used there) worked when i provided a wrong os that was not in my configuration.

## Second attempt: polarion marker calls a function that returns the appropriate polarion ID string
I created a dict where the key was the os and the value was a dict which contained also the polarion id.
i also created a function that would return the correct polarion id string according to the specific test case.
In this scenario the test function's parametrize section had the pytest.param list in place, so the generate_test_param function would only return the params and the convenience functions (generate_polarion_id, generate_skipif_params) would be called from each marker respectively.
In practice, I explicitly call pytest.mark.polarion in each test case and pass to it the generate_polarion_id function.
That worked when executing the test, but flake8 failed:

```
flake8...................................................................Failed
- hook id: flake8
- exit code: 1
Traceback (most recent call last):
  File "/home/ibesso/.cache/pre-commit/repo9tbcad3j/py_env-python3/bin/flake8", line 8, in <module>
    sys.exit(main())
  File "/home/ibesso/.cache/pre-commit/repo9tbcad3j/py_env-python3/lib/python3.6/site-packages/flake8/main/cli.py", line 22, in main
    app.run(argv)
  File "/home/ibesso/.cache/pre-commit/repo9tbcad3j/py_env-python3/lib/python3.6/site-packages/flake8/main/application.py", line 363, in run
    self._run(argv)
  File "/home/ibesso/.cache/pre-commit/repo9tbcad3j/py_env-python3/lib/python3.6/site-packages/flake8/main/application.py", line 351, in _run
    self.run_checks()
  File "/home/ibesso/.cache/pre-commit/repo9tbcad3j/py_env-python3/lib/python3.6/site-packages/flake8/main/application.py", line 264, in run_checks
    self.file_checker_manager.run()
  File "/home/ibesso/.cache/pre-commit/repo9tbcad3j/py_env-python3/lib/python3.6/site-packages/flake8/checker.py", line 323, in run
    self.run_serial()
  File "/home/ibesso/.cache/pre-commit/repo9tbcad3j/py_env-python3/lib/python3.6/site-packages/flake8/checker.py", line 307, in run_serial
    checker.run_checks()
  File "/home/ibesso/.cache/pre-commit/repo9tbcad3j/py_env-python3/lib/python3.6/site-packages/flake8/checker.py", line 589, in run_checks
    self.run_ast_checks()
  File "/home/ibesso/.cache/pre-commit/repo9tbcad3j/py_env-python3/lib/python3.6/site-packages/flake8/checker.py", line 494, in run_ast_checks
    for (line_number, offset, text, _) in runner:
  File "/home/ibesso/.cache/pre-commit/repo9tbcad3j/py_env-python3/lib/python3.6/site-packages/PolarionIds/__init__.py", line 227, in run
    f=f, polarion_id=elt_val.args[0].s
AttributeError: 'Call' object has no attribute 's'
```

## Third attempt: polarion marker accesses the dict that was created above in order to get the polarion ID string (the inner key's value)

In this step I did not use the convenience function, but directly accessed the dict in order to extract the polarion ID string.
A similar error was displayed:
```
flake8...................................................................Failed
- hook id: flake8
- exit code: 1
Traceback (most recent call last):
  File "/home/ibesso/.cache/pre-commit/repo9tbcad3j/py_env-python3/bin/flake8", line 8, in <module>
    sys.exit(main())
  File "/home/ibesso/.cache/pre-commit/repo9tbcad3j/py_env-python3/lib/python3.6/site-packages/flake8/main/cli.py", line 22, in main
    app.run(argv)
  File "/home/ibesso/.cache/pre-commit/repo9tbcad3j/py_env-python3/lib/python3.6/site-packages/flake8/main/application.py", line 363, in run
    self._run(argv)
  File "/home/ibesso/.cache/pre-commit/repo9tbcad3j/py_env-python3/lib/python3.6/site-packages/flake8/main/application.py", line 351, in _run
    self.run_checks()
  File "/home/ibesso/.cache/pre-commit/repo9tbcad3j/py_env-python3/lib/python3.6/site-packages/flake8/main/application.py", line 264, in run_checks
    self.file_checker_manager.run()
  File "/home/ibesso/.cache/pre-commit/repo9tbcad3j/py_env-python3/lib/python3.6/site-packages/flake8/checker.py", line 323, in run
    self.run_serial()
  File "/home/ibesso/.cache/pre-commit/repo9tbcad3j/py_env-python3/lib/python3.6/site-packages/flake8/checker.py", line 307, in run_serial
    checker.run_checks()
  File "/home/ibesso/.cache/pre-commit/repo9tbcad3j/py_env-python3/lib/python3.6/site-packages/flake8/checker.py", line 589, in run_checks
    self.run_ast_checks()
  File "/home/ibesso/.cache/pre-commit/repo9tbcad3j/py_env-python3/lib/python3.6/site-packages/flake8/checker.py", line 494, in run_ast_checks
    for (line_number, offset, text, _) in runner:
  File "/home/ibesso/.cache/pre-commit/repo9tbcad3j/py_env-python3/lib/python3.6/site-packages/PolarionIds/__init__.py", line 227, in run
    f=f, polarion_id=elt_val.args[0].s
AttributeError: 'Subscript' object has no attribute 's'
```

### Conclusions
* i did not see this usage anywhere in the code.
* The only other way i saw adding markers was in the pytest_collection_modifyitems pytest hook (tests/conftest.py), which is irrelevant.
* from my innocent attempt to debug the PolarionIds code, it seems that it expects this "s" attribute to exist in elt_val.args[0], but there is another level in which it could find that "s" attribute (elt_val.args[0].args[0] which held the arg i passed to the convenience function). most of this code does not make sense to me, so i did not dig deep and just tried to understand the error and where it failed.
* if removing this pre-commit check is out of the question, and if there is no other solution at hand, are we destined to always provide the polarion ID strings literraly and without any dynamic picking?

_Initially reported on slack here: https://coreos.slack.com/archives/C010TJVV3J4/p1626322631051100_

**Comment by myakove** [comment]
@ibesso-rh please provide a simple example that reproduce this error.
